# Travis CI file configuration
language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t octavio/react:latest -f Dockerfile.dev .

script:
  - docker run -e CI=true octavio/react:latest npm run test