# Travis CI file configuration
language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t OctavioArruda/docker-ci/cd-deploy -f Dockerfile.dev .

script:
  - docker run -e CI=true OctavioArruda/docker-ci/cd-deploy npm run test -- --coverage